export const SET_INGREDIENTS_SUCCESS = 'SET_INGREDIENTS_SUCCESS'
export const SET_INGREDIENTS_ERROR = 'SET_INGREDIENTS_ERROR'
export const SET_INGREDIENTS_REQUEST: 'SET_INGREDIENTS_REQUEST' = 'SET_INGREDIENTS_REQUEST'